#!/bin/bash
source ${SCRIPTS_DIR}/mgncs-configure

CC=${TARGET}gcc \
CXX=${TARGET}g++ \
LD=${TARGET}ld \
AS=${TARGET}as \
AR=${TARGET}ar \
LDFLAGS="${MINIGUI_LDFLAGS} ${BOARD_LDFLAGS}" \
CFLAGS="${MINIGUI_CFLAGS} ${BOARD_CFLAGS}" \
./configure --prefix=${PREFIX} \
		--build=${PLATFORM}-linux \
		--host=${PLATFORM}-linux \
		--target=${PLATFORM}-linux \
		${MGNCS_CONFIG}

make $MAKE_PARAM && make install && echo done
